### PR TITLE
Bug/fixedJitPackCompilation

### PR DESCRIPTION
**Pull request by kmalmur**

### CODE REVIEW

**Review by wzieba — APPROVED** [review]

**Comment by aminezghidi** [comment]
@kmalmur can you please explain the changes here? Do you remember what was the compilation error?

**Comment by kmalmur** [comment]
@aminezghidi as far as I remember, this lib was originally not using jitpack for publishing. As we created a fork, we decided to use jitpack so that we could easily compile and self publish the code

**Comment by kmalmur** [comment]
@aminezghidi btw, why asking this? is there any problem?

**Comment by aminezghidi** [comment]
> btw, why asking this? is there any problem?

@kmalmur the JetBrains annotations dependency used here is causing conflicts with `kotlin-stdlib` dependency we're using in `thefabulous-android`. I will handle that in the android repo but from what I see the dependency here is useless and not used.
Maybe I will update the repo later with the upstream as a new version is relesed.

**Comment by kmalmur** [comment]
@aminezghidi maybe you could exclude jetbrains dependency in top level gradle? https://stackoverflow.com/questions/41450496/gradle-exclude-nested-transitive-dependencies

**Pull request merged**
